### ISSUE TITLE
Add modern forest themed wall tile

### ISSUE THREAD

**Issue by arihantbansal** [fossasia/labyrinth#1008]
### Description

Create and add a new modern themed forest wall tile to the game.

### Implementation Plan

- [x] Find the wall you want to improve. It should be in [tiles/rooms/wall].
- [x] Copy the wall and edit it using [Inkscape]
- [x] Edit the [tiles.js] file to include the new wall in some pictures.

### Closing Criteria

- [ ] The wall is added to the labyrinth and reachable. Please provide the directions.

### Hints

- You might find the [documentation about adding new tiles] useful.

[documentation about adding new tiles]: https://github.com/fossasia/labyrinth#how-to-add-new-tiles
[tiles/rooms/wall]: https://github.com/fossasia/labyrinth/tree/master/tiles/rooms/wall
[tiles.js]: https://github.com/fossasia/labyrinth/blob/master/js/tiles.js
[Inkscape]: https://inkscape.org/
