### ISSUE TITLE
[Enable Tasks] Add music to tiles/game

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/labyrinth#245]
### Expected results

I would like to see two tasks about music in the tasks folder:
- adding music to a tile when you enter
- adding background music

### Actual results

There are no such tasks and there is no music.

Requirements:
- Tasks:
  - [x] adding music to a tile when you enter #262 
     - requirements to add
     - [X 100% self-made, add source files #316
  - [x] adding background music #267
     - requirements to add
     - [x] 100% self-made, add source files #315
- Task enabler:
  - add an API on how to play music, documentation first!
    - [X] for a tile #266
    - [x] for the background #284 
  - [X] implement the API
    - [X] for a tile #284 
    - [X] for the background #284 

Optional:
  - [ ] the music of any tile stops playing when the player **leaves** not moves
  - [ ] choose the background music randomly
  - [X] add a loudness to the background music in the object you store it. Some music may be loud, some music is quite silent. If we add music from different people, we want to control that in the game as they make music of different volume.
  - [ ] document different open-source software in the task that we can use.
    - recording: audacity

- [ ] When all is done, we can create a new feature task to show a configuration menu for the two music types (on off/loudness)

References:
- #206
  
 If you share a pull request with a descriptive title and #245 in the description as soon as you start, others will see the progress.

**Comment by saarthakchats** [comment]
Can me, @samyakbvs and @arjunpandey2003 collectively work on this.

**Comment by duttaditya18** [comment]
@niccokunzmann Can I work on adding an API? I think I'll able to do that.

**Comment by niccokunzmann** [comment]
Sure, please work on it. If you share a pull request with a descriptive title as soon as you start, others will see the progress.

**Comment by duttaditya18** [comment]
@niccokunzmann All right! I am starting to work on the API!

**Comment by arjunpandey2003** [comment]
I am adding the tasks

**Comment by arjunpandey2003** [comment]
so @duttaditya18 since you are making the API, we can co-operate, you have made the API, I have added the task, we will have enabled the task

**Comment by saarthakchats** [comment]
@niccokunzmann 
Working on it, adding sound effects.

**Comment by samyakbvs** [comment]
Adding some more sounds

**Comment by 0x48piraj** [comment]
Warming up my music consoles!

**Comment by niccokunzmann** [comment]
@samyakbvs Would you like to review my pull request #291 ?

**Comment by niccokunzmann** [comment]
Thanks for all the work. I want to review this and see how we can go further.

**Comment by duttaditya18** [comment]
@niccokunzmann I think all is done right here, I see a problem that the music stops after one is over. You have to manually click the buttons for going to a new song. I am working on that.

I think you can add it in this Issue only. I don't want to make a new issue.

However, the problem is that the only method I can come up with for solving this is check every second if the song has stopped or not. And if it is, then play a new one, but that makes this game much slower than it already is.

I also have plans for turning this into an Electron app. This would fix a lot of our slow loading problems and stuff.

**Comment by niccokunzmann** [comment]
Thanks for enabling the task. I will wait for #315 and #316 to be merged and then I will close this and split it up into different issues. Thanks for all other helpers reviewing and testing this!

**Comment by niccokunzmann** [comment]
I will close this now. Other ideas taken from this issue can be used to create other issues, see the optional part.
