### ISSUE TITLE
[WEEKATHON] Convert Tasks to Issue Templates

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/labyrinth#726]
### Expected results

Currently, we are not able to track the status of what people do while they solve a task.
Each issue is different if it is a bug report or a feature request. - tasks do not fit these issue statements.
We can use Templates to convert the [tasks](https://github.com/fossasia/labyrinth/tree/master/tasks) to issue templates and allow people to claim a task and make this visible.

Example:
https://github.com/FreifunkBremen/yanic/issues/new?template=community.md&title=Mention+community+$name

### Actual results

Currently, we have the tasks but can not give feedback on the tasks if someone does them.

### Implementation/Solution Ideas

See the other example.
- [x] use of checkmarks 
- [x] using details 

<details>
<summary>summary</summary>
more text

</details>

### Links

- https://help.github.com/articles/creating-an-issue-template-for-your-repository/#adding-multiple-issue-templates

### Would you like to work on this

Yes, but help is welcome!

### Implementation Plan

You can help me out:

- [x] add a functionality #738 
- [x] add a new feature  #738 
- [x] add background music  #738 
- [x] add music to tiles #740 
- [ ] add clues
- [x] cooperate on a pull request #738
- [ ] create a hand-drawn tile #740
- [ ] create a new level  #740
- [ ] create a new theme #740
- [ ] animate a tile #740
- [ ] create a wall #740
- [ ] create a character #740
- [ ] create a promotional video #740
- [ ] document how to contribute #740 
- [x] add new ways to contribute #738 
- [ ] enhance the game
- [ ] improve code quality #740
- [ ] improve the UI of the game #740 
- [ ] solve an advanced issue
- [ ] solve an issue
- [ ] create first timer issue #740

**Comment by himanshuc3** [comment]
Did not properly understand. 
Are you stating the the issues are redundant. And maybe linking of issues with there PRs.

**Comment by niccokunzmann** [comment]
@himanshuc3 I edited the description. Is it clearer now?

**Comment by himanshuc3** [comment]
Yup, a sound tone now!
