### ISSUE TITLE
New Character: PixelArt Thumbs Up

### ISSUE THREAD

**Issue by AppleC4T** [fossasia/labyrinth#754]
### Description

A green (matching the navbar color) thumbs up made with pixel-art.

### Implementation Plan

- [x] Read the [documentation about adding characters].
- [x] Create a character of correct dimensions with a drawing program such as [Inkscape].
- [x] Upload the character to the [characters folder].
- [x] Add the character path to the [gui.js] file between the other characters.

### Closing Criteria

- [ ] The character is added to the menu to choose characters which is
  shown once the game starts.
- [ ] The image is in the correct folder.

[documentation about adding characters]: https://github.com/fossasia/labyrinth#how-to-add-a-new-character
[characters folder]: https://github.com/fossasia/labyrinth/tree/master/characters
[gio.js]: https://github.com/fossasia/labyrinth/blob/master/js/gui.js#L47
[Inkscape]: https://inkscape.org/
