### ISSUE TITLE
New Tile: Seaside view

### ISSUE THREAD

**Issue by AppleC4T** [fossasia/labyrinth#766]
### Description

Add a new tile with a sea graphic on walls

### Implementation Plan

- [x] Read the [documentation about adding new tiles].
- [x] Draw a floor.
- [x] Draw a wall.
- [x] Draw another wall or mirror the existing one.
- [ ] Scan or photograph the pictures if they are hand-drawn.
- [x] Add the pictures to the [tiles folder].
- [x] Edit the [tiles.js] file to include the new tile.
- [x] Place the tile in the labyrinth.
- [ ] Check that you can not walk through walls in the code and the labyrinth.

### Closing Criteria

- [ ] The tile is added to the labyrinth and reachable. Please provide the directions.
- [ ] The tile is properly rendered.

[documentation about adding new tiles]: https://github.com/fossasia/labyrinth#how-to-add-new-tiles
[tiles folder]: https://github.com/fossasia/labyrinth/tree/master/tiles
[tiles.js]: https://github.com/fossasia/labyrinth/blob/master/js/tiles.js
