### ISSUE TITLE
New Tile Sound: dark glitched music

### ISSUE THREAD

**Issue by AppleC4T** [fossasia/labyrinth#850]
### Description

Add a mysterious/glitched music to the dark glowing tile.

### Implementation Plan

- [x] Compose or play the music or sound and record it.
  - You can record sounds using [Audacity]
  - You can use [Sonic Pi] to program the sound.
- [x] Add one file containing the song to the [/audio] folder.
- [x] Add the license as a file according to [documentation]
- [x] Add it to the API in the [tiles.js] file.

### Closing Criteria

- [x] When we enter the tile, the music plays.
  - [x] Check the browser console for errors.
  - [x] Provide the way to the tile.
- The license of the music is
  - [x] in the file next to the music so it belongs to the music file without doubt:
    same file name + `.license`

### Hints

- For your own recordings, we recommend choosing the license `CC-BY` or `CC-BY-SA` if you
  like others to remix or `CC-BY-ND` if you do not like people editing your song.
  Choose a license here: https://creativecommons.org/choose/
  Please do not choose NC as this might disable it for GSoC.

[/audio]: https://github.com/fossasia/labyrinth/tree/master/audio
[documentation]: https://rawgit.com/fossasia/labyrinth/master/documentation/#API-Adding-New-Music
[tiles.js]: https://github.com/fossasia/labyrinth/tree/master/js/tiles.js
[Audacity]: https://www.audacityteam.org/
[Sonic Pi]: http://sonic-pi.net/

**Comment by YashKumarVerma** [comment]
Thanks for your contribution
