### ISSUE TITLE
Add a Hand Drawn Tile

### ISSUE THREAD

**Issue by akshit15013** [fossasia/labyrinth#856]
### Description

Create a PR to add a hand drawn tile

### Implementation Plan

- [x] Read the [documentation about adding new tiles].
- [x] Draw a floor.
- [ ] Draw a wall.
- [x] Draw another wall or mirror the existing one.
- [x] Scan or photograph the pictures if they are hand-drawn.
- [x] Add the pictures to the [tiles folder].
- [x] Edit the [tiles.js] file to include the new tile.
- [x] Place the tile in the labyrinth.
- [x] Check that you can not walk through walls in the code and the labyrinth.

### Closing Criteria

- [x] The tile is added to the labyrinth and reachable. Please provide the directions.
- [x] The tile is properly rendered.

[documentation about adding new tiles]: https://github.com/fossasia/labyrinth#how-to-add-new-tiles
[tiles folder]: https://github.com/fossasia/labyrinth/tree/master/tiles
[tiles.js]: https://github.com/fossasia/labyrinth/blob/master/js/tiles.js

**Comment by YashKumarVerma** [comment]
Please follow the Template.

**Comment by akshit15013** [comment]
@YashKumarVerma

**Comment by YashKumarVerma** [comment]
Thanks for the changes @akshit15013 . I think we can close it now.
