### ISSUE TITLE
New Character: Iron Man

### ISSUE THREAD

**Issue by niteshkumarniranjan** [fossasia/labyrinth#857]
### Description
Iron Man

### Implementation Plan

- [x] Read the [documentation about adding characters].
- [x] Create a character of correct dimensions with a drawing program such as [Inkscape].
- [x] Upload the character to the [characters folder].
- [x] Add the character path to the [gui.js] file between the other characters.

### Closing Criteria

- [x] The character is added to the menu to choose characters which is
  shown once the game starts.
- [x] The image is in the correct folder.

[documentation about adding characters]: https://github.com/fossasia/labyrinth#how-to-add-a-new-character
[characters folder]: https://github.com/fossasia/labyrinth/tree/master/characters
[gui.js]: https://github.com/fossasia/labyrinth/blob/master/js/gui.js#L47
[Inkscape]: https://inkscape.org/
