### ISSUE TITLE
Add a hand drawn tile

### ISSUE THREAD

**Issue by akshit15013** [fossasia/labyrinth#862]
### Implementation Plan

- [ ] Read the [documentation about adding new tiles].
- [ ] Draw a floor.
- [ ] Draw a wall.
- [ ] Draw another wall or mirror the existing one.
- [ ] Scan or photograph the pictures if they are hand-drawn.
- [ ] Add the pictures to the [tiles folder].
- [ ] Edit the [tiles.js] file to include the new tile.
- [ ] Place the tile in the labyrinth.
- [ ] Check that you can not walk through walls in the code and the labyrinth.

### Closing Criteria

- [ ] The tile is added to the labyrinth and reachable. Please provide the directions.
- [ ] The tile is properly rendered.

[documentation about adding new tiles]: https://github.com/fossasia/labyrinth#how-to-add-new-tiles
[tiles folder]: https://github.com/fossasia/labyrinth/tree/master/tiles
[tiles.js]: https://github.com/fossasia/labyrinth/blob/master/js/tiles.js

**Comment by YashKumarVerma** [comment]
Closing as Duplicate of #856
