### ISSUE TITLE
Add My Own Music

### ISSUE THREAD

**Issue by pythongiant** [fossasia/labyrinth#864]
### Implementation Plan

- [ ] Compose or play the music and record it.
  - You can sing or play an instrument like guitar and piano and record it using [Audacity]
  - You can use [Sonic Pi] to program the music.
- [x] Add one file containing the song to the [/audio/background] folder.
- [x] Add the license as a file according to [documentation]
- [x] Add it to the API in the [sound.js] file.

### Closing Criteria

- [x] We can choose your music from the music menu. Provide the name.
- The license of the music is
  - [] in the file next to the music so it belongs to the music file without doubt:
    same file name + `.license`
  - [x] added to the [sound.js] file so we can give credit to the artist while
    playing the music.

### Hints

- For your own recordings, we recommend choosing the license `CC-BY` or `CC-BY-SA` if you
  like others to remix or `CC-BY-ND` if you do not like people editing your song.
  Choose a license here: https://creativecommons.org/choose/
  Please do not choose NC as this might disable it for GSoC.

[/audio/background]: https://github.com/fossasia/labyrinth/tree/master/audio/background
[documentation]: https://rawgit.com/fossasia/labyrinth/master/documentation/#API-Adding-New-Music
[sound.js]: https://github.com/fossasia/labyrinth/tree/master/js/sound.js
[Audacity]: https://www.audacityteam.org/
[Sonic Pi]: http://sonic-pi.net/

**Comment by YashKumarVerma** [comment]
Please fill the description

**Comment by pythongiant** [comment]
Well its NCS and I followed their guidelines @YashKumarVerma
