### ISSUE TITLE
New Level: Dark Realm

### ISSUE THREAD

**Issue by AppleC4T** [fossasia/labyrinth#868]
### Description

Add a new level based on the dark glowing tile

### Implementation Plan

- [x] Read the [documentation about adding new tiles].
- [x] Create a new level in [levels.js].
- [x] Create or modify a tile which allows switching to your level in [tiles.js].

### Closing Criteria

- [x] The level is added to the labyrinth and reachable. Please provide the path.
- [x] One can walk through the level.

[documentation about adding new tiles]: https://github.com/fossasia/labyrinth#how-to-add-new-tiles
[tiles.js]: https://github.com/fossasia/labyrinth/blob/master/js/tiles.js
[levels.js]: https://github.com/fossasia/labyrinth/blob/master/js/levels.js
