### ISSUE TITLE
Add Dog Character

### ISSUE THREAD

**Issue by Mattythewie** [fossasia/labyrinth#875]
### Description
Added a dog character.

### Implementation Plan

- [ ]  Read the documentation about adding characters.
- [ ]  Create a character of correct dimensions with a drawing program such as Inkscape.
- [ ]  Upload the character to the characters folder.
- [ ]  Add the character path to the gui.js file between the other characters.

### Closing Criteria

- [ ]  The character is added to the menu to choose characters which is shown once the game starts.
- [ ]  The image is in the correct folder.

**Comment by YashKumarVerma** [comment]
# :tada: Good Work
