### ISSUE TITLE
Add animated Tile

### ISSUE THREAD

**Issue by pythongiant** [fossasia/labyrinth#891]
### Description

Add an animated tile

### Implementation Plan

- [x] Read the [documentation about animating tiles].
- [x] Choose the a tile or part of it from the [tiles folder].
- [x] Edit the SVG file determine the Id of the element you like to animate or add it with this Id.
- [x] Edit the SVG file as text and add `<style>` to it.
- [x] Animate your tile according to the [documentation about animating tiles]

### Closing Criteria

- [X] The tile has an animation. Please provide a link to the tile. [ tiles/rooms/floor/quake.svg ]

[tiles folder]: https://github.com/fossasia/labyrinth/tree/master/tiles
[documentation about animating tiles]: https://github.com/fossasia/labyrinth#how-to-animate-a-tile
