### ISSUE TITLE
Add character: LittleAlien

### ISSUE THREAD

**Issue by lunamana104** [fossasia/labyrinth#900]
### Description

Add a Little Alien (pretty weird tho) character to the game!

### Implementation Plan

- [x] Read the [documentation about adding characters].
- [x] Create a character of correct dimensions with a drawing program such as [Inkscape].
- [x] Upload the character to the [characters folder].
- [x] Add the character path to the [gui.js] file between the other characters.

### Closing Criteria

- [x] The character is added to the menu to choose characters which is
  shown once the game starts.
- [x] The image is in the correct folder.

[documentation about adding characters]: https://github.com/fossasia/labyrinth#how-to-add-a-new-character
[characters folder]: https://github.com/fossasia/labyrinth/tree/master/characters
[gui.js]: https://github.com/fossasia/labyrinth/blob/master/js/gui.js#L47
[Inkscape]: https://inkscape.org/

**Comment by YashKumarVerma** [comment]
Labyrinth has a set of Issue Templates to standardize the development.

Consider using them. That can be found at 
https://github.com/fossasia/labyrinth/tree/master/.github/ISSUE_TEMPLATE

Thanks for your contribution to the community.

**Comment by lunamana104** [comment]
can you merge my PR now? @YashKumarVerma 
https://github.com/fossasia/labyrinth/pull/904
