### ISSUE TITLE
Feature Request : Discovered tiles tracker

### ISSUE THREAD

**Issue by AppleC4T** [fossasia/labyrinth#902]
### How to use the Feature
The feature would add a counter to the game's side menu that would track how many new tiles the player has discovered (i.e. how many times the player walked into a new, previously invisible tile) during the current run.

### How the Feature Improves the Game
The discovered tiles tracker could act as:
- a type of score/statistic to share (player may get badges for discovering a certain amount of tiles)
- a winning/progress condition (some levels may require the player to discover a given number of tiles before it becomes available to enter)
### Implementation/Solution Ideas
Implementation:
- [x] add a script checking whether the player has seen a tile previously or not
- [x] add a script tracking the new, discovered tiles
- [x] add methods allowing to make conditions based on the number of discovered tiles
- [x] add a counter to the side menu
### Would you like to work on this
Yes, the whole feature is almost ready for implementation, what I need now is your feedback.

**Comment by AppleC4T** [comment]
@abishekvashok @YashKumarVerma I'm especially eager to see your feedback, since you are the maintainers.

**Comment by abishekvashok** [comment]
It would be nice in my opinion

**Comment by YashKumarVerma** [comment]
Creative indeed. We surely need this feature as the game progresses. Keep up the great work
