### ISSUE TITLE
Add a level Partytime

### ISSUE THREAD

**Issue by akshit15013** [fossasia/labyrinth#906]
### Description

Create a PR to add a level Partytime

### Implementation Plan

- [x] Read the [documentation about adding new tiles].
- [x] Create a new level in [levels.js].
- [x] Create or modify a tile which allows switching to your level in [tiles.js].

### Closing Criteria

- [x] The level is added to the labyrinth and reachable. Please provide the path.
- [x] One can walk through the level.
