### ISSUE TITLE
Add an animated tile

### ISSUE THREAD

**Issue by akshit15013** [fossasia/labyrinth#920]
### Description

Create a PR to add an animated tile to the labyrinth maze

### Implementation Plan

- [x] Read the [documentation about animating tiles].
- [x] Choose the a tile or part of it from the [tiles folder].
- [x] Edit the SVG file determine the Id of the element you like to animate or add it with this Id.
- [x] Edit the SVG file as text and add `<style>` to it.
- [x] Animate your tile according to the [documentation about animating tiles]

### Closing Criteria

- [x] The tile has an animation. Please provide a link to the tile.
