### ISSUE TITLE
Add a Rabbit Character

### ISSUE THREAD

**Issue by Ryan10145** [fossasia/labyrinth#959]
### Description

A gray rabbit

### Implementation Plan

- [X] Read the [documentation about adding characters].
- [X] Create a character of correct dimensions with a drawing program such as [Inkscape].
- [X] Upload the character to the [characters folder].
- [X] Add the character path to the [gui.js] file between the other characters.

### Closing Criteria

- [X] The character is added to the menu to choose characters which is
  shown once the game starts.
- [X] The image is in the correct folder.

[documentation about adding characters]: https://github.com/fossasia/labyrinth#how-to-add-a-new-character
[characters folder]: https://github.com/fossasia/labyrinth/tree/master/characters
[gui.js]: https://github.com/fossasia/labyrinth/blob/master/js/gui.js#L47
[Inkscape]: https://inkscape.org/
