### ISSUE TITLE
Add a new Old Room Tile

### ISSUE THREAD

**Issue by Ryan10145** [fossasia/labyrinth#970]
### Description

- Add a new tile that includes a mysterious looking old, decrepit room that has a clean floor

### Implementation Plan

- [X] Read the [documentation about adding new tiles].
- [X] Draw a floor.
- [X] Draw a wall.
- [ ] Draw another wall or mirror the existing one.
- [ ] Scan or photograph the pictures if they are hand-drawn.
- [X] Add the pictures to the [tiles folder].
- [X] Edit the [tiles.js] file to include the new tile.
- [X] Place the tile in the labyrinth.
- [X] Check that you can not walk through walls in the code and the labyrinth.

### Closing Criteria

- [ ] The tile is added to the labyrinth and reachable. Please provide the directions.
- [ ] The tile is properly rendered.

[documentation about adding new tiles]: https://github.com/fossasia/labyrinth#how-to-add-new-tiles
[tiles folder]: https://github.com/fossasia/labyrinth/tree/master/tiles
[tiles.js]: https://github.com/fossasia/labyrinth/blob/master/js/tiles.js
