### ISSUE TITLE
Added a New Character Larva

### ISSUE THREAD

**Issue by Jeewal** [fossasia/labyrinth#972]
### Description
larva is a simple character.

### Implementation Plan
- [x] Read the https://github.com/fossasia/labyrinth#how-to-add-a-new-character
- [x] Created a character of correct dimensions with a drawing program such as https://inkscape.org/
- [x] Uploaded the character to the https://github.com/fossasia/labyrinth/tree/master/characters.
- [x] Added the character path to the https://github.com/fossasia/labyrinth/blob/master/js/gui.js#L47 file between the other characters.

### Closing Criteria
- [x] The character is added to the menu to choose characters which is shown once the game starts.
- [x] The image is in the correct folder.
