### ISSUE TITLE
Add a new hand drawn tile

### ISSUE THREAD

**Issue by NishithP2004** [fossasia/labyrinth#975]
### Implementation Plan

- [x] Read the [documentation about adding new tiles].
- [x] Draw a floor.
- [x] Draw a wall.
- [x] Draw another wall or mirror the existing one.
- [x] Scan or photograph the pictures if they are hand-drawn.
- [x] Add the pictures to the [tiles folder].
- [x] Edit the [tiles.js] file to include the new tile.
- [x] Place the tile in the labyrinth.
- [x] Check that you can not walk through walls in the code and the labyrinth.

### Closing Criteria

- [x] The tile is added to the labyrinth and reachable. Please provide the directions.
- [x] The tile is properly rendered.
